Repository LibrePCB/LibrePCB, pull requests merged in 2018-08, with the labels that each got.

#299 Add command-line tool "librepcb-cli"
  apps/apps.pro
  apps/librepcb-cli/commandlineinterface.cpp
  apps/librepcb-cli/commandlineinterface.h
  apps/librepcb-cli/librepcb-cli.pro
  apps/librepcb-cli/main.cpp
  apps/librepcb/controlpanel/controlpanel.cpp
  apps/librepcb/projectlibraryupdater/projectlibraryupdater.cpp
  ci/build.sh
  ci/test.sh
  libs/librepcb/project/boards/boardgerberexport.cpp
  libs/librepcb/project/boards/boardgerberexport.h
  libs/librepcb/project/project.cpp
  libs/librepcb/project/project.h
  libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp
  tests/unittests/project/boards/boardplanefragmentsbuildertest.cpp
  tests/unittests/project/projecttest.cpp
Labels: enhancement

#301 Mark many strings as non-translatable
  apps/EagleImport/mainwindow.ui
  apps/WorkspaceLibraryUpdater/mainwindow.ui
  apps/librepcb/firstrunwizard/firstrunwizardpage_workspacepath.ui
  libs/librepcb/libraryeditor/cmp/componenteditorwidget.ui
  libs/librepcb/libraryeditor/cmpcat/componentcategoryeditorwidget.ui
  libs/librepcb/libraryeditor/common/componentchooserdialog.ui
  libs/librepcb/libraryeditor/common/packagechooserdialog.ui
  libs/librepcb/libraryeditor/common/symbolchooserdialog.ui
  libs/librepcb/libraryeditor/dev/deviceeditorwidget.ui
  libs/librepcb/libraryeditor/lib/libraryoverviewwidget.ui
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_deviceproperties.ui
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_entermetadata.ui
  libs/librepcb/libraryeditor/pkg/packageeditorwidget.ui
  libs/librepcb/libraryeditor/pkgcat/packagecategoryeditorwidget.ui
  libs/librepcb/libraryeditor/sym/dialogs/symbolpinpropertiesdialog.ui
  libs/librepcb/libraryeditor/sym/symboleditorwidget.ui
  libs/librepcb/librarymanager/libraryinfowidget.ui
  libs/librepcb/librarymanager/librarylistwidgetitem.ui
  libs/librepcb/projecteditor/boardeditor/boardlayersdock.ui
  libs/librepcb/projecteditor/boardeditor/boardplanepropertiesdialog.ui
  libs/librepcb/projecteditor/boardeditor/boardviapropertiesdialog.ui
  libs/librepcb/projecteditor/boardeditor/deviceinstancepropertiesdialog.ui
  libs/librepcb/projecteditor/dialogs/projectpropertieseditordialog.ui
  libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_initialization.ui
  libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_metadata.ui
  libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
Labels: i18n / l10n

#315 Refactor ProjectLibrary to fix several issues
  libs/librepcb/library/librarybaseelement.cpp
  libs/librepcb/project/library/projectlibrary.cpp
  libs/librepcb/project/library/projectlibrary.h
  tests/unittests/library/librarybaseelementtest.cpp
  tests/unittests/project/library/projectlibrarytest.cpp
  tests/unittests/unittests.pro
Labels: enhancement, refactoring

#317 Fix broken FilePath::isRoot() on Windows, possibly causing application crash
  libs/librepcb/common/fileio/filepath.cpp
  tests/unittests/common/filepathtest.cpp
Labels: os-windows
