Repository LibrePCB/LibrePCB, pull requests merged in 2018-09, with the labels that each got.

#326 Doxygen: Add release workflow documentation
  dev/doxygen/gitgraph/.gitignore
  dev/doxygen/gitgraph/README.md
  dev/doxygen/gitgraph/release_workflow_diagram.html
  dev/doxygen/gitgraph/release_workflow_diagram.js
  dev/doxygen/images/release_workflow_diagram.png
  dev/doxygen/pages/mainpage.md
  dev/doxygen/pages/release_workflow.md
  dev/doxygen/pages/versioning.md
Labels: documentation

#334 AppVeyor: Use ccache to speed up builds
  appveyor.yml
  ci/install_dependencies.sh
Labels: ci, os-windows

#320 Allow dragging symbols by circular grab areas
  libs/librepcb/project/schematics/graphicsitems/sgi_symbol.cpp
Labels: bug
