Repository LibrePCB/LibrePCB, pull requests merged in 2018-10, with the labels that each got.

#337 Hide UUIDs in many windows and dialogs
  libs/librepcb/libraryeditor/cmp/componenteditorwidget.cpp
  libs/librepcb/libraryeditor/cmp/componenteditorwidget.ui
  libs/librepcb/libraryeditor/cmpcat/componentcategoryeditorwidget.cpp
  libs/librepcb/libraryeditor/cmpcat/componentcategoryeditorwidget.h
  libs/librepcb/libraryeditor/cmpcat/componentcategoryeditorwidget.ui
  libs/librepcb/libraryeditor/common/componentchooserdialog.cpp
  libs/librepcb/libraryeditor/common/componentchooserdialog.ui
  libs/librepcb/libraryeditor/common/packagechooserdialog.cpp
  libs/librepcb/libraryeditor/common/packagechooserdialog.ui
  libs/librepcb/libraryeditor/common/symbolchooserdialog.cpp
  libs/librepcb/libraryeditor/common/symbolchooserdialog.ui
  libs/librepcb/libraryeditor/dev/deviceeditorwidget.cpp
  libs/librepcb/libraryeditor/dev/deviceeditorwidget.ui
  libs/librepcb/libraryeditor/lib/librarylisteditorwidget.cpp
  libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp
  libs/librepcb/libraryeditor/lib/libraryoverviewwidget.ui
  libs/librepcb/libraryeditor/libraryeditor.cpp
  libs/librepcb/libraryeditor/libraryeditor.h
  libs/librepcb/libraryeditor/libraryeditor.ui
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_deviceproperties.cpp
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_deviceproperties.h
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_deviceproperties.ui
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_entermetadata.cpp
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_entermetadata.h
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_entermetadata.ui
  libs/librepcb/libraryeditor/pkg/packageeditorwidget.cpp
  libs/librepcb/libraryeditor/pkg/packageeditorwidget.ui
  libs/librepcb/libraryeditor/pkgcat/packagecategoryeditorwidget.cpp
  libs/librepcb/libraryeditor/pkgcat/packagecategoryeditorwidget.h
  libs/librepcb/libraryeditor/pkgcat/packagecategoryeditorwidget.ui
  libs/librepcb/libraryeditor/sym/dialogs/symbolpinpropertiesdialog.cpp
  libs/librepcb/libraryeditor/sym/dialogs/symbolpinpropertiesdialog.ui
  libs/librepcb/libraryeditor/sym/symboleditorwidget.cpp
  libs/librepcb/libraryeditor/sym/symboleditorwidget.ui
  libs/librepcb/librarymanager/libraryinfowidget.cpp
  libs/librepcb/librarymanager/libraryinfowidget.ui
  libs/librepcb/librarymanager/repositorylibrarylistwidgetitem.cpp
  libs/librepcb/projecteditor/boardeditor/boardplanepropertiesdialog.cpp
  libs/librepcb/projecteditor/boardeditor/boardplanepropertiesdialog.ui
  libs/librepcb/projecteditor/boardeditor/boardviapropertiesdialog.cpp
  libs/librepcb/projecteditor/boardeditor/boardviapropertiesdialog.ui
  libs/librepcb/projecteditor/boardeditor/deviceinstancepropertiesdialog.cpp
  libs/librepcb/projecteditor/boardeditor/deviceinstancepropertiesdialog.ui
  libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.cpp
  libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
  libs/librepcb/workspace/workspace.cpp
  libs/librepcb/workspace/workspace.h
Labels: UI / UX

#338 Doxygen: Add documentation about file format upgrade
  dev/doxygen/pages/project.md
  dev/doxygen/pages/workspace.md
Labels: documentation

#353 SchematicEditor: Add print support
  libs/librepcb/project/project.cpp
  libs/librepcb/project/project.h
  libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp
  libs/librepcb/projecteditor/schematiceditor/schematiceditor.h
  libs/librepcb/projecteditor/schematiceditor/schematiceditor.ui
Labels: enhancement

#358 Mark many strings as nontranslatable
  libs/librepcb/common/attributes/attrtypecapacitance.cpp
  libs/librepcb/common/attributes/attrtypefrequency.cpp
  libs/librepcb/common/attributes/attrtypeinductance.cpp
  libs/librepcb/common/attributes/attrtyperesistance.cpp
  libs/librepcb/common/attributes/attrtypevoltage.cpp
  libs/librepcb/common/dialogs/boarddesignrulesdialog.ui
  libs/librepcb/common/dialogs/stroketextpropertiesdialog.ui
  libs/librepcb/common/units/lengthunit.cpp
  libs/librepcb/projecteditor/boardeditor/boardviapropertiesdialog.ui
  libs/librepcb/projecteditor/boardeditor/deviceinstancepropertiesdialog.ui
  libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
Labels: i18n / l10n
