Repository LibrePCB/LibrePCB, pull requests merged in 2019-07, with the labels that each got.

#471 Fix possible crash caused by low-level signal/slots
  libs/librepcb/common/signalslot.h
  tests/unittests/common/signalslottest.cpp
  tests/unittests/unittests.pro
Labels: bug

#479 Fix inconsistent appearance of polygons between editor and Gerber export
  libs/librepcb/common/graphics/polygongraphicsitem.cpp
  libs/librepcb/library/pkg/footprintpreviewgraphicsitem.cpp
  libs/librepcb/library/pkg/packagecheck.cpp
  libs/librepcb/library/sym/symbolpreviewgraphicsitem.cpp
  libs/librepcb/project/boards/boardgerberexport.cpp
  libs/librepcb/project/boards/graphicsitems/bgi_footprint.cpp
  libs/librepcb/project/schematics/graphicsitems/sgi_symbol.cpp
Labels: bug

#484 About dialog: Mark TEXT_CONTRIBUTE_CODE as nontranslatable
  libs/librepcb/common/dialogs/aboutdialog.ui
Labels: i18n / l10n

#477 GraphicsView: Implement pinch to zoom
  libs/librepcb/common/graphics/graphicsview.cpp
  libs/librepcb/common/graphics/graphicsview.h
Labels: UI / UX, enhancement

#487 Add toggle in the menu bar for dock widgets
  libs/librepcb/projecteditor/boardeditor/boardeditor.cpp
  libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp
Labels: UI / UX, enhancement
