Repository LibrePCB/LibrePCB, pull requests merged in 2019-04, with the labels that each got.

#439 Library Editor: Fix height issues of various dialogs
  libs/librepcb/libraryeditor/common/componentchooserdialog.ui
  libs/librepcb/libraryeditor/common/packagechooserdialog.ui
  libs/librepcb/libraryeditor/common/symbolchooserdialog.ui
Labels: UI / UX, bug, enhancement, os-windows

#443 Add search field to symbol/package/component chooser dialogs
  libs/librepcb/libraryeditor/common/componentchooserdialog.cpp
  libs/librepcb/libraryeditor/common/componentchooserdialog.h
  libs/librepcb/libraryeditor/common/componentchooserdialog.ui
  libs/librepcb/libraryeditor/common/packagechooserdialog.cpp
  libs/librepcb/libraryeditor/common/packagechooserdialog.h
  libs/librepcb/libraryeditor/common/packagechooserdialog.ui
  libs/librepcb/libraryeditor/common/symbolchooserdialog.cpp
  libs/librepcb/libraryeditor/common/symbolchooserdialog.h
  libs/librepcb/libraryeditor/common/symbolchooserdialog.ui
  libs/librepcb/workspace/library/workspacelibrarydb.cpp
  libs/librepcb/workspace/library/workspacelibrarydb.h
Labels: UI / UX, enhancement

#440 Update default layer colors
  libs/librepcb/common/graphics/graphicslayer.cpp
Labels: enhancement

#444 AddComponentDialog: Refactor and improve search
  libs/librepcb/projecteditor/dialogs/addcomponentdialog.cpp
  libs/librepcb/projecteditor/dialogs/addcomponentdialog.h
  libs/librepcb/workspace/library/workspacelibrarydb.cpp
  libs/librepcb/workspace/library/workspacelibrarydb.h
Labels: UI / UX, enhancement
