Repository LibrePCB/LibrePCB, pull requests merged in 2019-06, with the labels that each got.

#458 CI: Replace Travis-CI with Azure Pipelines
  .travis.yml
  README.md
  appveyor.yml
  ci/azure-jobs-doxygen.yml
  ci/azure-jobs-linux.yml
  ci/azure-jobs-macos.yml
  ci/azure-jobs-stylecheck.yml
  ci/azure-pipelines.yml
  ci/build.sh
  ci/build_doxygen.sh
  ci/build_installer.sh
  ci/build_librepcb.sh
  ci/build_linux_appimage.sh
  ci/build_mac_bundle.sh
  ci/build_windows_archive.sh
  ci/install_dependencies.sh
  ci/test.sh
  ci/upload_artifacts.sh
Labels: ci, os-linux, os-macos

#464 BoardEditor: Fix unintended tool change after double click on footprint
  libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp
Labels: bug

#467 Enable scrolling with both axis when pressing Ctrl
  libs/librepcb/common/graphics/graphicsview.cpp
Labels: UI / UX, enhancement

#470 Automatically choose next free numerical pad name
  libs/librepcb/library/pkg/packagepadlistmodel.cpp
  libs/librepcb/library/pkg/packagepadlistmodel.h
Labels: UI / UX, enhancement
