Repository LibrePCB/LibrePCB, pull requests merged in 2019-12, with the labels that each got.

#613 Update appdata file
  dev/doxygen/pages/release_workflow.md
  share/metainfo/org.librepcb.LibrePCB.appdata.xml
Labels: development, documentation

#625 Remove WorkspaceLibraryUpdater application
  apps/README.md
  apps/WorkspaceLibraryUpdater/WorkspaceLibraryUpdater.pro
  apps/WorkspaceLibraryUpdater/main.cpp
  apps/WorkspaceLibraryUpdater/mainwindow.cpp
  apps/WorkspaceLibraryUpdater/mainwindow.h
  apps/WorkspaceLibraryUpdater/mainwindow.ui
  apps/apps.pro
Labels: refactoring

#537 Fix doxygen build warnings
  dev/doxygen/Doxyfile
  dev/doxygen/pages/code_style_guide.md
  dev/doxygen/pages/mainpage.md
  dev/doxygen/pages/repository.md
  dev/doxygen/pages/workspace.md
  libs/librepcb/common/attributes/attributeprovider.h
  libs/librepcb/common/attributes/attributesubstitutor.h
  libs/librepcb/common/attributes/attributetype.h
  libs/librepcb/common/cam/gerbergenerator.h
  libs/librepcb/common/dialogs/gridsettingsdialog.h
  libs/librepcb/common/exceptions.h
  libs/librepcb/common/fileio/directorylock.h
  libs/librepcb/common/fileio/filepath.h
  libs/librepcb/common/fileio/fileutils.h
  libs/librepcb/common/fileio/serializableobjectlist.h
  libs/librepcb/common/network/networkrequestbase.h
  libs/librepcb/common/systeminfo.h
  libs/librepcb/common/undostack.h
  libs/librepcb/common/units/angle.h
  libs/librepcb/common/units/length.h
  libs/librepcb/common/units/lengthunit.h
  libs/librepcb/common/units/point.h
  libs/librepcb/common/uuid.h
  libs/librepcb/common/version.h
  libs/librepcb/libraryeditor/libraryeditor.h
  libs/librepcb/project/boards/boardlayerstack.h
  libs/librepcb/project/boards/items/bi_base.h
  libs/librepcb/project/circuit/circuit.h
  libs/librepcb/project/circuit/componentinstance.h
  libs/librepcb/project/erc/if_ercmsgprovider.h
  libs/librepcb/project/project.h
  libs/librepcb/project/schematics/items/si_base.h
  libs/librepcb/project/schematics/schematic.h
  libs/librepcb/project/schematics/schematiclayerprovider.h
  libs/librepcb/projecteditor/boardeditor/fsm/bes_fsm.h
  libs/librepcb/projecteditor/boardeditor/fsm/boardeditorevent.h
  libs/librepcb/projecteditor/projecteditor.h
  libs/librepcb/projecteditor/schematiceditor/fsm/schematiceditorevent.h
  libs/librepcb/projecteditor/schematiceditor/fsm/ses_fsm.h
  libs/librepcb/workspace/settings/items/wsi_projectautosaveinterval.h
  libs/librepcb/workspace/workspace.h
Labels: documentation

#636 Fix Qt 5.14 deprecation warnings
  libs/librepcb/common/fileio/transactionalfilesystem.cpp
  libs/librepcb/common/toolbox.h
  libs/librepcb/project/boards/board.cpp
  libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp
  libs/librepcb/projecteditor/boardeditor/unplacedcomponentsdock.cpp
  libs/librepcb/projecteditor/cmd/cmdflipselectedboarditems.cpp
  libs/librepcb/projecteditor/cmd/cmdremoveboarditems.cpp
  libs/librepcb/projecteditor/cmd/cmdremoveselectedschematicitems.cpp
  libs/librepcb/projecteditor/dialogs/editnetclassesdialog.cpp
  libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.cpp
  libs/librepcb/workspace/library/workspacelibraryscanner.cpp
  tests/unittests/common/fileio/transactionalfilesystemtest.cpp
Labels: ci, os-macos

#635 CI: Use Ubuntu 18.04 for the Doxygen job
  ci/azure-jobs-doxygen.yml
  dev/doxygen/Doxyfile
  libs/librepcb/common/fileio/filepath.h
  libs/librepcb/librarymanager/librarydownload.h
  libs/librepcb/project/boards/boardlayerstack.h
Labels: ci, documentation

#637 Fix regex of various constrained strings
  libs/librepcb/common/attributes/attributekey.h
  libs/librepcb/common/circuitidentifier.h
  libs/librepcb/common/graphics/graphicslayername.h
  libs/librepcb/common/uuid.cpp
  libs/librepcb/library/cmp/componentprefix.h
  libs/librepcb/library/cmp/componentsymbolvariantitemsuffix.h
  tests/unittests/common/attributes/attributekeytest.cpp
  tests/unittests/common/circuitidentifiertest.cpp
  tests/unittests/common/graphics/graphicslayernametest.cpp
  tests/unittests/common/uuidtest.cpp
  tests/unittests/library/cmp/componentprefixtest.cpp
  tests/unittests/library/cmp/componentsymbolvariantitemsuffixtest.cpp
  tests/unittests/unittests.pro
Labels: bug

#638 Library Editor: Support moving elements to other library
  img/actions/move_to.png
  img/images.qrc
  libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp
  libs/librepcb/libraryeditor/lib/libraryoverviewwidget.h
Labels: UI / UX, enhancement
