Repository LibrePCB/LibrePCB, pull requests merged in 2019-10, with the labels that each got.

#524 Initialize *.lppz export filename with default value
  libs/librepcb/projecteditor/projecteditor.cpp
Labels: UI / UX, enhancement

#525 Board editor: Add device context menu item "Snap to grid"
  libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp
Labels: UI / UX, enhancement

#531 Board editor: Allow to hide copper planes
  img/actions/hide_planes.png
  img/actions/show_planes.png
  img/images.qrc
  libs/librepcb/project/boards/graphicsitems/bgi_plane.cpp
  libs/librepcb/project/boards/items/bi_plane.cpp
  libs/librepcb/project/boards/items/bi_plane.h
  libs/librepcb/projecteditor/boardeditor/boardeditor.cpp
  libs/librepcb/projecteditor/boardeditor/boardeditor.h
  libs/librepcb/projecteditor/boardeditor/boardeditor.ui
  libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp
Labels: UI / UX, enhancement

#532 Schematic editor: Provide more options when renaming net segments
  libs/librepcb/projecteditor/projecteditor.pro
  libs/librepcb/projecteditor/schematiceditor/fsm/ses_select.cpp
  libs/librepcb/projecteditor/schematiceditor/renamenetsegmentdialog.cpp
  libs/librepcb/projecteditor/schematiceditor/renamenetsegmentdialog.h
  libs/librepcb/projecteditor/schematiceditor/renamenetsegmentdialog.ui
Labels: UI / UX, enhancement

#533 Board editor: Allow rotate while moving items
  libs/librepcb/project/boards/cmd/cmdboardnetpointedit.cpp
  libs/librepcb/project/boards/cmd/cmdboardnetpointedit.h
  libs/librepcb/project/boards/cmd/cmdboardviaedit.cpp
  libs/librepcb/project/boards/cmd/cmdboardviaedit.h
  libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp
  libs/librepcb/projecteditor/boardeditor/fsm/bes_select.h
  libs/librepcb/projecteditor/cmd/cmddragselectedboarditems.cpp
  libs/librepcb/projecteditor/cmd/cmddragselectedboarditems.h
  libs/librepcb/projecteditor/cmd/cmdmoveselectedboarditems.h
  libs/librepcb/projecteditor/cmd/cmdrotateselectedboarditems.cpp
  libs/librepcb/projecteditor/projecteditor.pro
Labels: UI / UX, enhancement

#555 Library editor: Remove underscore from placeholders
  libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_drawtextbase.cpp
  libs/librepcb/libraryeditor/sym/fsm/symboleditorstate_drawtextbase.cpp
Labels: UI / UX

#559 If clang-format fails, show hint about the --docker flag
  dev/format_code.sh
Labels: development

#561 Schematic editor: Fix device when adding component multiple times
  libs/librepcb/projecteditor/schematiceditor/fsm/ses_addcomponent.cpp
  libs/librepcb/projecteditor/schematiceditor/fsm/ses_addcomponent.h
Labels: bug

#563 LibraryEditor: Fix missing message box when closing tab
  libs/librepcb/libraryeditor/libraryeditor.cpp
Labels: UI / UX, bug

#565 Schematic editor: Allow changing pre-selected device of components
  libs/librepcb/project/circuit/cmd/cmdcomponentinstanceedit.cpp
  libs/librepcb/project/circuit/cmd/cmdcomponentinstanceedit.h
  libs/librepcb/project/circuit/componentinstance.cpp
  libs/librepcb/project/circuit/componentinstance.h
  libs/librepcb/projecteditor/schematiceditor/fsm/ses_select.cpp
  libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.cpp
  libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.h
  libs/librepcb/projecteditor/schematiceditor/symbolinstancepropertiesdialog.ui
Labels: UI / UX, enhancement, tool-schematics-editor

#564 Board editor: Tool to measure wire length
  img/README.md
  img/actions/ruler.png
  img/images.qrc
  libs/librepcb/common/dialogs/aboutdialog.cpp
  libs/librepcb/common/dialogs/aboutdialog.ui
  libs/librepcb/common/fileio/filepath.h
  libs/librepcb/common/toolbox.cpp
  libs/librepcb/common/toolbox.h
  libs/librepcb/common/units/point.h
  libs/librepcb/project/boards/items/bi_netline.cpp
  libs/librepcb/project/boards/items/bi_netline.h
  libs/librepcb/project/schematics/items/si_netsegment.cpp
  libs/librepcb/projecteditor/boardeditor/fsm/bes_select.cpp
  libs/librepcb/projecteditor/boardeditor/fsm/bes_select.h
  libs/librepcb/projecteditor/cmd/cmdremoveselectedschematicitems.cpp
  libs/librepcb/projecteditor/schematiceditor/fsm/ses_select.cpp
  libs/librepcb/projecteditor/schematiceditor/fsm/ses_select.h
Labels: enhancement, tool-board-editor
