Repository LibrePCB/LibrePCB, pull requests merged in 2019-08, with the labels that each got.

#491 Auto-select attribute unit when entering unit in value field
  libs/librepcb/common/attributes/attributelistmodel.cpp
  libs/librepcb/common/attributes/attributetype.cpp
  libs/librepcb/common/attributes/attributetype.h
  libs/librepcb/common/attributes/attributeunit.cpp
  libs/librepcb/common/attributes/attributeunit.h
  libs/librepcb/common/attributes/attrtypecapacitance.cpp
  libs/librepcb/common/attributes/attrtypecurrent.cpp
  libs/librepcb/common/attributes/attrtypefrequency.cpp
  libs/librepcb/common/attributes/attrtypeinductance.cpp
  libs/librepcb/common/attributes/attrtypepower.cpp
  libs/librepcb/common/attributes/attrtyperesistance.cpp
  libs/librepcb/common/attributes/attrtypevoltage.cpp
  libs/librepcb/projecteditor/schematiceditor/fsm/ses_addcomponent.cpp
Labels: UI / UX, enhancement

#501 Fix missing plane cut-out for board outlines in footprints
  libs/librepcb/project/boards/boardplanefragmentsbuilder.cpp
Labels: bug, gerber

#502 Board editor: Fix invisible zero-width circles/polygons
  libs/librepcb/project/boards/graphicsitems/bgi_footprint.cpp
Labels: bug

#503 Fix broken window settings when closing windows with OpenGL enabled
  libs/librepcb/common/graphics/graphicsview.cpp
  tests/funq/aliases
  tests/funq/conftest.py
  tests/funq/projecteditor/test_window_settings.py
  tests/funq/requirements.txt
Labels: UI / UX, bug

#504 Gerber: Always use multi-quadrant mode
  libs/librepcb/common/cam/gerbergenerator.cpp
  libs/librepcb/common/cam/gerbergenerator.h
Labels: bug, gerber
