Repository LibrePCB/LibrePCB, pull requests merged in 2020-05, with the labels that each got.

#691 CI: Update Linux and macOS build environment
  ci/azure-jobs-linux.yml
  ci/install_dependencies.sh
Labels: ci, deployment, os-linux, os-macos

#692 Fix empty table row in pick&place and BOM export dialogs
  libs/librepcb/projecteditor/boardeditor/boardpickplacegeneratordialog.cpp
  libs/librepcb/projecteditor/dialogs/bomgeneratordialog.cpp
Labels: UI / UX, bug

#693 Library editor: Disable "move to other library" if empty
  libs/librepcb/libraryeditor/lib/libraryoverviewwidget.cpp
Labels: UI / UX, enhancement

#694 Support configuring PDF viewer in workspace settings
  libs/librepcb/projecteditor/boardeditor/boardeditor.cpp
  libs/librepcb/projecteditor/schematiceditor/schematiceditor.cpp
  libs/librepcb/workspace/settings/workspacesettings.cpp
  libs/librepcb/workspace/settings/workspacesettings.h
  libs/librepcb/workspace/settings/workspacesettingsdialog.cpp
  libs/librepcb/workspace/settings/workspacesettingsdialog.ui
Labels: UI / UX, enhancement, file format, tool-board-editor, tool-schematics-editor

#703 Doxygen: Show TOC on markdown pages
  dev/doxygen/Doxyfile
Labels: development, documentation

#702 Move model-view classes from library to library::editor
  libs/librepcb/library/library.pro
  libs/librepcb/libraryeditor/cmp/componentpinsignalmapmodel.cpp
  libs/librepcb/libraryeditor/cmp/componentpinsignalmapmodel.h
  libs/librepcb/libraryeditor/cmp/componentsignallisteditorwidget.cpp
  libs/librepcb/libraryeditor/cmp/componentsignallisteditorwidget.h
  libs/librepcb/libraryeditor/cmp/componentsignallistmodel.cpp
  libs/librepcb/libraryeditor/cmp/componentsignallistmodel.h
  libs/librepcb/libraryeditor/cmp/componentsymbolvarianteditdialog.cpp
  libs/librepcb/libraryeditor/cmp/componentsymbolvarianteditdialog.h
  libs/librepcb/libraryeditor/cmp/componentsymbolvariantitemlisteditorwidget.cpp
  libs/librepcb/libraryeditor/cmp/componentsymbolvariantitemlisteditorwidget.h
  libs/librepcb/libraryeditor/cmp/componentsymbolvariantitemlistmodel.cpp
  libs/librepcb/libraryeditor/cmp/componentsymbolvariantitemlistmodel.h
  libs/librepcb/libraryeditor/cmp/componentsymbolvariantlistmodel.cpp
  libs/librepcb/libraryeditor/cmp/componentsymbolvariantlistmodel.h
  libs/librepcb/libraryeditor/cmp/componentsymbolvariantlistwidget.cpp
  libs/librepcb/libraryeditor/cmp/componentsymbolvariantlistwidget.h
  libs/librepcb/libraryeditor/cmp/compsymbvarpinsignalmapeditorwidget.cpp
  libs/librepcb/libraryeditor/cmp/compsymbvarpinsignalmapeditorwidget.h
  libs/librepcb/libraryeditor/dev/devicepadsignalmapmodel.cpp
  libs/librepcb/libraryeditor/dev/devicepadsignalmapmodel.h
  libs/librepcb/libraryeditor/dev/padsignalmapeditorwidget.cpp
  libs/librepcb/libraryeditor/dev/padsignalmapeditorwidget.h
  libs/librepcb/libraryeditor/libraryeditor.pro
  libs/librepcb/libraryeditor/libraryelementcache.cpp
  libs/librepcb/libraryeditor/libraryelementcache.h
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_componentpinsignalmap.cpp
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_componentsymbols.cpp
  libs/librepcb/libraryeditor/pkg/footprintlisteditorwidget.cpp
  libs/librepcb/libraryeditor/pkg/footprintlisteditorwidget.h
  libs/librepcb/libraryeditor/pkg/footprintlistmodel.cpp
  libs/librepcb/libraryeditor/pkg/footprintlistmodel.h
  libs/librepcb/libraryeditor/pkg/packagepadlisteditorwidget.cpp
  libs/librepcb/libraryeditor/pkg/packagepadlisteditorwidget.h
  libs/librepcb/libraryeditor/pkg/packagepadlistmodel.cpp
  libs/librepcb/libraryeditor/pkg/packagepadlistmodel.h
Labels: refactoring
