Repository LibrePCB/LibrePCB, pull requests merged in 2020-10, with the labels that each got.

#788 UuidGenerator: Add quazip build dependency
  apps/UuidGenerator/UuidGenerator.pro
Labels: bug, build system

#786 BoardDesignRules: Fix loading max. stopmask drill diameter
  libs/librepcb/common/boarddesignrules.cpp
  tests/unittests/common/boarddesignrulestest.cpp
  tests/unittests/unittests.pro
Labels: bug, tool-board-editor

#794 Board editor: Fix staying in the "place device" tool
  libs/librepcb/projecteditor/boardeditor/fsm/boardeditorfsm.cpp
  libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate.h
  libs/librepcb/projecteditor/boardeditor/fsm/boardeditorstate_adddevice.cpp
Labels: UI / UX, bug, tool-board-editor

#789 Only set QUAZIP_STATIC for static builds
  common.pri
Labels: bug, build system

#779 Use built-in markdown support when using Qt >=5.14
  apps/librepcb-cli/librepcb-cli.pro
  apps/librepcb/librepcb.pro
  apps/librepcb/markdown/markdownconverter.cpp
  ci/azure-jobs-linux.yml
  libs/libs.pro
Labels: refactoring

#797 CI: Work around broken macOS builds
  ci/install_dependencies.sh
Labels: ci, os-macos

#796 Fix missing holes in footprint previews
  libs/librepcb/common/graphics/holegraphicsitem.cpp
  libs/librepcb/common/graphics/holegraphicsitem.h
  libs/librepcb/library/pkg/footprintpreviewgraphicsitem.cpp
  libs/librepcb/libraryeditor/pkg/fsm/cmd/cmddragselectedfootprintitems.cpp
  libs/librepcb/libraryeditor/pkg/fsm/packageeditorstate_select.cpp
Labels: UI / UX, bug, tool-board-editor, tool-library-editor, tool-schematics-editor
