Repository LibrePCB/LibrePCB, pull requests merged in 2020-01, with the labels that each got.

#643 Fix missing resources in QtCreator designer
  apps/EagleImport/EagleImport.pro
  apps/UuidGenerator/UuidGenerator.pro
  apps/librepcb-cli/librepcb-cli.pro
  apps/librepcb/controlpanel/controlpanel.ui
  apps/librepcb/firstrunwizard/firstrunwizard.ui
  apps/librepcb/librepcb.pro
  dev/sort_qmake_file_entries.py
  libs/librepcb/common/common.pro
  libs/librepcb/eagleimport/eagleimport.pro
  libs/librepcb/library/library.pro
  libs/librepcb/libraryeditor/cmpcat/componentcategoryeditorwidget.ui
  libs/librepcb/libraryeditor/dev/deviceeditorwidget.ui
  libs/librepcb/libraryeditor/lib/librarylisteditorwidget.ui
  libs/librepcb/libraryeditor/libraryeditor.pro
  libs/librepcb/libraryeditor/newelementwizard/newelementwizard.ui
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_choosetype.ui
  libs/librepcb/libraryeditor/newelementwizard/newelementwizardpage_entermetadata.ui
  libs/librepcb/libraryeditor/pkgcat/packagecategoryeditorwidget.ui
  libs/librepcb/librarymanager/librarymanager.pro
  libs/librepcb/project/project.pro
  libs/librepcb/projecteditor/dialogs/bomgeneratordialog.ui
  libs/librepcb/projecteditor/dialogs/projectsettingsdialog.ui
  libs/librepcb/projecteditor/docks/ercmsgdock.ui
  libs/librepcb/projecteditor/newprojectwizard/newprojectwizardpage_metadata.ui
  libs/librepcb/projecteditor/projecteditor.pro
  libs/librepcb/projecteditor/schematiceditor/schematicpagesdock.ui
  libs/librepcb/workspace/workspace.pro
Labels: development

#647 Fix outdated development resources
  README.md
  dev/README.md
  dev/docker/Dockerfile
  dev/docker/LibrePCB.conf
  dev/docker/README.md
  dev/docker/build_container.sh
  dev/docker/make_librepcb.sh
  dev/docker/run_container.sh
  dev/docker/startup.sh
Labels: development, documentation

#650 Doxygen: Add database schema diagram
  dev/.gitignore
  dev/diagrams/lib_db.dia
  dev/diagrams/svg/lib_db.svg
  dev/doxygen/images/database_diagram.png
  dev/doxygen/pages/workspace.md
  dev/generate_db_schema_diagram.sh
Labels: development, documentation

#623 README: Add BSD to the Features section
  README.md
Labels: documentation

#649 Change macOS default target directory
  dist/installer/update_metadata.sh
Labels: bug, os-macos
