Repository LibrePCB/LibrePCB, pull requests merged in 2022-11, with the labels that each got.

#1062 Add .git-blame-ignore-revs file
  .git-blame-ignore-revs
Labels: development

#1063 CLI: Use -v for --verbose instead of --version.
  apps/librepcb-cli/commandlineinterface.cpp
  tests/cli/open_library/test_parser.py
  tests/cli/open_project/test_parser.py
  tests/cli/test_help.py
Labels: tool-cli

#1067 Remove obsolete workspace settings after file format upgrade
  libs/librepcb/core/workspace/workspacesettings.cpp
  libs/librepcb/core/workspace/workspacesettings.h
  tests/unittests/core/workspace/workspacesettingstest.cpp
Labels: enhancement

#1068 SExpression: Remove support for legacy formatting
  libs/librepcb/core/project/board/board.cpp
  libs/librepcb/core/project/circuit/circuit.cpp
  libs/librepcb/core/project/erc/ercmsglist.cpp
  libs/librepcb/core/project/project.cpp
  libs/librepcb/core/project/projectsettings.cpp
  libs/librepcb/core/project/schematic/schematic.cpp
  libs/librepcb/core/serialization/serializablekeyvaluemap.h
  libs/librepcb/core/serialization/serializableobject.h
  libs/librepcb/core/serialization/sexpression.cpp
  libs/librepcb/core/serialization/sexpression.h
  libs/librepcb/core/workspace/workspacesettings.cpp
  libs/librepcb/core/workspace/workspacesettingsitem_genericvaluelist.h
  libs/librepcb/core/workspace/workspacesettingsitem_keyboardshortcuts.cpp
  libs/librepcb/editor/workspace/controlpanel/favoriteprojectsmodel.cpp
  libs/librepcb/editor/workspace/controlpanel/recentprojectsmodel.cpp
  tests/unittests/CMakeLists.txt
  tests/unittests/core/project/board/boardplanefragmentsbuildertest.cpp
  tests/unittests/core/serialization/serializableobjectlisttest.cpp
  tests/unittests/core/serialization/sexpressionlegacymode.h
  tests/unittests/core/serialization/sexpressiontest.cpp
  tests/unittests/core/utils/tangentpathjoinertest.cpp
  tests/unittests/core/workspace/workspacesettingstest.cpp
Labels: file format
