Repository LibrePCB/LibrePCB, pull requests merged in 2023-09, with the labels that each got.

#1219 Show OpenCascade version in about dialog
  apps/librepcb-cli/commandlineinterface.cpp
  cmake/FindOpenCascade.cmake
  libs/librepcb/core/3d/occmodel.cpp
  libs/librepcb/core/3d/occmodel.h
  libs/librepcb/core/build_env.h.in
  libs/librepcb/editor/dialogs/aboutdialog.cpp
  tests/cli/test_version.py
Labels: enhancement, UI / UX

#1222 CLI: Implement new command 'open-step'
  apps/librepcb-cli/commandlineinterface.cpp
  apps/librepcb-cli/commandlineinterface.h
  libs/librepcb/core/3d/occmodel.cpp
  libs/librepcb/core/3d/occmodel.h
  tests/cli/conftest.py
  tests/cli/open_step/test_minify.py
  tests/cli/open_step/test_open.py
  tests/cli/open_step/test_parser.py
  tests/cli/open_step/test_tesselate.py
  tests/cli/test_help.py
Labels: enhancement, tool-cli

#1223 3D view: Fix location and color of some STEP solids
  libs/librepcb/core/3d/occmodel.cpp
  tests/cli/open_step/test_tesselate.py
Labels: bug, UI / UX, tool-board-editor, tool-library-editor

#1224 Board editor: Fix highlighting pads while drawing traces
  libs/librepcb/editor/project/boardeditor/boardgraphicsscene.cpp
  libs/librepcb/editor/project/boardeditor/graphicsitems/bgi_footprintpad.cpp
  libs/librepcb/editor/project/boardeditor/graphicsitems/bgi_footprintpad.h
Labels: bug, UI / UX, tool-board-editor

#1225 CI: Update to latest Docker images
  ci/azure-jobs-linux.yml
  ci/azure-jobs-windows.yml
Labels: ci

#1226 Fix possibly broken STEP files after minification
  libs/librepcb/core/3d/occmodel.cpp
  tests/unittests/core/3d/occmodeltest.cpp
Labels: bug, tool-library-editor

#1227 Make list_tests.py callable from within subfolder
  AUTHORS.md
  dev/list_tests.py
Labels: development

#1228 AUTHORS.md: Update list of contributors
  AUTHORS.md
  dev/update_contributors.py
Labels: documentation

#1230 Change backticks to POSIX style
  dev/capture_overview_screenshot.sh
  dev/capture_screenshots.sh
  dev/diagrams/convert.sh
  dev/graphics/convert.sh
Labels: development

#1235 Fix FileUtils::getFilesInDirectory() reveal nested hidden files
  libs/librepcb/core/fileio/fileutils.cpp
Labels: bug

#1237 Use std::hypot() for Point::getLength() calculation
  libs/librepcb/core/types/point.h
  tests/unittests/core/types/pointtest.cpp
Labels: bug
