Repository LibrePCB/LibrePCB, pull requests merged in 2023-08, with the labels that each got.

#1185 ERC: Warn about schematic wires with open end
  libs/librepcb/core/project/erc/electricalrulecheck.cpp
  libs/librepcb/core/project/erc/electricalrulecheck.h
  libs/librepcb/core/project/erc/electricalrulecheckmessages.cpp
  libs/librepcb/core/project/erc/electricalrulecheckmessages.h
  libs/librepcb/core/project/schematic/items/si_netline.h
  libs/librepcb/core/project/schematic/items/si_netpoint.h
  libs/librepcb/core/project/schematic/items/si_symbolpin.h
Labels: enhancement, tool-schematics-editor

#1186 Workpace upgrade wizard: Allow switching workspace
  libs/librepcb/editor/workspace/initializeworkspacewizard/initializeworkspacewizard.cpp
  libs/librepcb/editor/workspace/initializeworkspacewizard/initializeworkspacewizard_upgrade.cpp
Labels: enhancement, UI / UX

#1190 Add component dialog: Automatically select first search result
  libs/librepcb/editor/project/addcomponentdialog.cpp
  libs/librepcb/editor/project/addcomponentdialog.h
  libs/librepcb/editor/project/addcomponentdialog.ui
Labels: enhancement, UI / UX, tool-schematics-editor

#1193 Board editor: Fix context menu of selected devices
  libs/librepcb/editor/project/boardeditor/fsm/boardeditorstate_select.cpp
Labels: bug, enhancement, UI / UX, tool-board-editor

#1192 About dialog: Add credits section
  img/images.qrc
  img/logo/ngi0-entrust.png
  libs/librepcb/editor/dialogs/aboutdialog.cpp
  libs/librepcb/editor/dialogs/aboutdialog.ui
Labels: UI / UX

#1187 Upgrade all libraries file format during background scan
  libs/librepcb/core/fileio/fileutils.cpp
  libs/librepcb/core/fileio/fileutils.h
  libs/librepcb/core/fileio/transactionalfilesystem.cpp
  libs/librepcb/core/fileio/transactionalfilesystem.h
  libs/librepcb/core/library/cat/componentcategory.cpp
  libs/librepcb/core/library/cat/componentcategory.h
  libs/librepcb/core/library/cat/packagecategory.cpp
  libs/librepcb/core/library/cat/packagecategory.h
  libs/librepcb/core/library/cmp/component.cpp
  libs/librepcb/core/library/cmp/component.h
  libs/librepcb/core/library/dev/device.cpp
  libs/librepcb/core/library/dev/device.h
  libs/librepcb/core/library/library.cpp
  libs/librepcb/core/library/library.h
  libs/librepcb/core/library/pkg/package.cpp
  libs/librepcb/core/library/pkg/package.h
  libs/librepcb/core/library/sym/symbol.cpp
  libs/librepcb/core/library/sym/symbol.h
  libs/librepcb/core/project/projectloader.cpp
  libs/librepcb/core/workspace/workspacelibraryscanner.cpp
  libs/librepcb/core/workspace/workspacelibraryscanner.h
  libs/librepcb/editor/workspace/initializeworkspacewizard/initializeworkspacewizard_upgrade.ui
  tests/unittests/core/fileio/transactionalfilesystemtest.cpp
Labels: enhancement, file format

#1196 Add a QtQuick test window
  CMakeLists.txt
  apps/librepcb/main.cpp
  ci/azure-jobs-macos.yml
  ci/build_linux_portables.sh
  ci/build_mac_bundle.sh
  ci/build_windows_archive.sh
  dev/doxygen/pages/building.md
  libs/librepcb/core/build_env.h.in
  libs/librepcb/editor/CMakeLists.txt
  libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp
  libs/librepcb/editor/workspace/controlpanel/controlpanel.h
  share/librepcb/qml/testwindow.qml
Labels: deployment, UI / UX

#1197 ShortcutsReferenceGenerator: Fix layout overflow
  libs/librepcb/editor/utils/shortcutsreferencegenerator.cpp
  libs/librepcb/editor/utils/shortcutsreferencegenerator.h
  tests/unittests/editor/utils/shortcutsreferencegeneratortest.cpp
Labels: bug, enhancement

#1199 Add alternative names to packages file format
  libs/librepcb/core/library/pkg/package.cpp
  libs/librepcb/core/library/pkg/package.h
  libs/librepcb/core/workspace/workspacelibrarydb.cpp
  libs/librepcb/core/workspace/workspacelibrarydb.h
  libs/librepcb/core/workspace/workspacelibrarydbwriter.cpp
  libs/librepcb/core/workspace/workspacelibrarydbwriter.h
  libs/librepcb/core/workspace/workspacelibraryscanner.cpp
Labels: enhancement, file format

#1200 Simplify development & release workflow
  CONTRIBUTING.md
  dev/doxygen/gitgraph/.gitignore
  dev/doxygen/gitgraph/README.md
  dev/doxygen/gitgraph/release_workflow_diagram.html
  dev/doxygen/gitgraph/release_workflow_diagram.js
  dev/doxygen/images/development_cycle_diagram.png
  dev/doxygen/images/release_workflow_diagram.png
  dev/doxygen/pages/release_workflow.md
Labels: documentation, deployment

#1202 Support opening *.lppz projects with the editor
  dist/installer/packages/librepcb.registerfileextensions/meta/installscript.qs
  libs/librepcb/editor/project/boardeditor/boardeditor.cpp
  libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp
  libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp
  libs/librepcb/editor/workspace/controlpanel/fileiconprovider.cpp
  share/icons/hicolor/scalable/mimetypes/org.librepcb.LibrePCB-archive.svg
  share/mime/packages/org.librepcb.LibrePCB.xml
  tests/funq/commandline/test_open_project.py
Labels: enhancement, deployment

#1210 Fix using legacy 'PARTNUMBER' attribute as default value
  libs/librepcb/core/library/cmp/componentcheckmessages.cpp
  libs/librepcb/eagleimport/eaglelibraryimport.cpp
  libs/librepcb/editor/library/cmp/componenteditorwidget.cpp
Labels: bug, tool-library-editor

#1211 WorkspaceLibraryScanner: Do not warn about empty directories
  libs/librepcb/core/library/library.cpp
  libs/librepcb/core/workspace/workspacelibraryscanner.cpp
Labels: enhancement

#1213 Library editor: Fix possible layout issue of banner
  libs/librepcb/editor/library/cmp/componenteditorwidget.ui
  libs/librepcb/editor/library/pkg/packageeditorwidget.ui
  libs/librepcb/editor/library/sym/symboleditorwidget.ui
Labels: bug, UI / UX, tool-library-editor

#1214 Fix possibly broken copy&paste in editors on some systems
  libs/librepcb/editor/library/pkg/footprintclipboarddata.cpp
  libs/librepcb/editor/library/sym/symbolclipboarddata.cpp
  libs/librepcb/editor/project/boardeditor/boardclipboarddata.cpp
  libs/librepcb/editor/project/schematiceditor/schematicclipboarddata.cpp
Labels: bug, tool-board-editor, tool-schematics-editor, tool-library-editor

#1209 CI: Make build_mac_bundle.sh working on Apple Silicon
  ci/build_mac_bundle.sh
Labels: deployment, os-macos

#1208 OpenGlView: Fix compile error on missing OpenGL defines
  libs/librepcb/editor/widgets/openglview.cpp
Labels: bug

#1207 DesktopServices: Support using (custom) xdg-open command
  libs/librepcb/editor/workspace/desktopservices.cpp
Labels: bug, enhancement, deployment

#1215 Use lighter red/yellow background colors in parts table
  libs/librepcb/editor/library/dev/partlistmodel.cpp
  libs/librepcb/editor/project/componentassemblyoptionlisteditorwidget.cpp
Labels: enhancement, UI / UX, tool-board-editor, tool-schematics-editor

#1212 Suppress warning on stderr caused by argv[0]
  libs/librepcb/editor/workspace/controlpanel/controlpanel.cpp
  libs/librepcb/editor/workspace/controlpanel/controlpanel.h
Labels: enhancement

#1216 Show deprecated library elements with red color
  libs/librepcb/editor/library/cmp/componentchooserdialog.cpp
  libs/librepcb/editor/library/lib/libraryoverviewwidget.cpp
  libs/librepcb/editor/library/pkg/packagechooserdialog.cpp
  libs/librepcb/editor/library/sym/symbolchooserdialog.cpp
  libs/librepcb/editor/project/addcomponentdialog.cpp
  libs/librepcb/editor/project/addcomponentdialog.h
Labels: enhancement, UI / UX

#1221 Improve metainfo file
  share/metainfo/org.librepcb.LibrePCB.metainfo.xml
Labels: deployment, os-linux
