Repository LibrePCB/LibrePCB, pull requests merged in 2024-05, with the labels that each got.

#1383 Change keyboard shortcuts PDF location to cache directory
  libs/librepcb/editor/utils/standardeditorcommandhandler.cpp
Labels: bug, deployment, os-linux

#1384 Fix license identifier in AppStream Metainfo XML
  share/metainfo/org.librepcb.LibrePCB.metainfo.xml
Labels: deployment

#1385 Drop support for Qt < 5.12 and CMake < 3.16
  CMakeLists.txt
  README.md
  apps/librepcb/main.cpp
  dev/doxygen/pages/code_style_guide.md
  libs/librepcb/core/geometry/path.cpp
  libs/librepcb/core/network/orderpcbapirequest.cpp
  libs/librepcb/core/serialization/serializableobjectlist.h
  libs/librepcb/editor/editorcommand.cpp
  libs/librepcb/editor/library/dev/padsignalmapeditorwidget.cpp
  libs/librepcb/editor/project/schematiceditor/schematiceditor.cpp
  libs/librepcb/editor/utils/editortoolbox.cpp
  libs/librepcb/editor/workspace/workspacesettingsdialog.cpp
  tests/unittests/editor/dialogs/graphicsexportdialogtest.cpp
  tests/unittests/testhelpers.h
Labels: development, build system

#1389 Fix possibly wrong language of theme color names
  libs/librepcb/core/workspace/theme.cpp
  libs/librepcb/core/workspace/theme.h
  libs/librepcb/core/workspace/themecolor.cpp
  libs/librepcb/core/workspace/themecolor.h
Labels: bug, UI / UX

#1392 STEP export: Include all PCB outlines, if multiple
  libs/librepcb/core/3d/stepexport.cpp
Labels: bug, export

#1395 Replace pick&place icon from Icons8
  .reuse/dep5
  img/actions/export_pick_place_file.png
Labels: UI / UX
