Repository LibrePCB/LibrePCB, pull requests merged in 2024-06, with the labels that each got.

#1397 CI: Re-enable QtQuick test window for Windows and macOS
  ci/azure-jobs-macos.yml
  ci/azure-jobs-windows.yml
  ci/azure-pipelines.yml
  ci/build_librepcb.sh
  ci/build_mac_bundle.sh
  ci/clean.sh
Labels: ci, deployment, os-windows, os-macos

#1391 Implement automatic dark theme for Windows
  apps/librepcb/main.cpp
Labels: os-windows, UI / UX

#1401 STEP export: Fix possibly wrong placement of devices
  libs/librepcb/core/3d/occmodel.cpp
Labels: bug, export

#1404 Update REUSE copyright metadata
  .reuse/dep5
Labels: documentation

#1407 Fix colors of BOM/PnP table rows with dark theme
  libs/librepcb/editor/project/boardeditor/boardpickplacegeneratordialog.cpp
  libs/librepcb/editor/project/bomgeneratordialog.cpp
Labels: bug, UI / UX, tool-schematics-editor

#1408 Give GUI higher thread priority than background tasks
  apps/librepcb/main.cpp
  libs/librepcb/core/network/networkaccessmanager.cpp
  libs/librepcb/core/workspace/workspacelibraryscanner.cpp
Labels: enhancement, UI / UX

#1411 Schematic editor: Ask for swapping component names
  libs/librepcb/editor/project/schematiceditor/symbolinstancepropertiesdialog.cpp
Labels: enhancement, UI / UX, tool-schematics-editor
